"""Theme system: schema, loading, and ANSI color resolution.

Ported from `packages/coding-agent/src/modes/interactive/theme/` in the
TypeScript "pi" monorepo. See `theme.py` for what is and is not ported.
"""

from __future__ import annotations

from pi_coding_agent.modes.interactive.theme.theme import (
    THEME_BG_KEYS,
    THEME_COLOR_KEYS,
    AutoThemeSetting,
    ColorMode,
    ColorValue,
    RgbColor,
    TerminalAutoThemeDetector,
    TerminalBackgroundThemeDetector,
    TerminalTheme,
    TerminalThemeDetection,
    Theme,
    ThemeExportColors,
    ThemeInfo,
    ThemeResult,
    ansi256_to_hex,
    bg_ansi,
    detect_terminal_background_from_env,
    detect_terminal_background_theme,
    detect_terminal_theme_for_auto,
    fg_ansi,
    get_available_themes,
    get_available_themes_with_paths,
    get_default_theme,
    get_markdown_theme,
    get_resolved_theme_colors,
    get_select_list_theme,
    get_settings_list_theme,
    get_theme_by_name,
    get_theme_export_colors,
    get_theme_for_rgb_color,
    hex_to_256,
    hex_to_rgb,
    init_theme,
    is_light_theme,
    load_theme,
    load_theme_from_path,
    on_theme_change,
    parse_auto_theme_setting,
    resolve_theme_colors,
    resolve_theme_setting,
    resolve_var_refs,
    rgb_to_256,
    set_registered_themes,
    set_theme,
    set_theme_instance,
    theme,
    with_theme_color_fallbacks,
)
from pi_coding_agent.modes.interactive.theme.theme_controller import InteractiveThemeController

__all__ = [
    "THEME_BG_KEYS",
    "THEME_COLOR_KEYS",
    "AutoThemeSetting",
    "ColorMode",
    "ColorValue",
    "InteractiveThemeController",
    "RgbColor",
    "TerminalAutoThemeDetector",
    "TerminalBackgroundThemeDetector",
    "TerminalTheme",
    "TerminalThemeDetection",
    "Theme",
    "ThemeExportColors",
    "ThemeInfo",
    "ThemeResult",
    "ansi256_to_hex",
    "bg_ansi",
    "detect_terminal_background_from_env",
    "detect_terminal_background_theme",
    "detect_terminal_theme_for_auto",
    "fg_ansi",
    "get_available_themes",
    "get_available_themes_with_paths",
    "get_default_theme",
    "get_markdown_theme",
    "get_resolved_theme_colors",
    "get_select_list_theme",
    "get_settings_list_theme",
    "get_theme_by_name",
    "get_theme_export_colors",
    "get_theme_for_rgb_color",
    "hex_to_256",
    "hex_to_rgb",
    "init_theme",
    "is_light_theme",
    "load_theme",
    "load_theme_from_path",
    "on_theme_change",
    "parse_auto_theme_setting",
    "resolve_theme_colors",
    "resolve_theme_setting",
    "resolve_var_refs",
    "rgb_to_256",
    "set_registered_themes",
    "set_theme",
    "set_theme_instance",
    "theme",
    "with_theme_color_fallbacks",
]
